name: Lint

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install Dependencies
        run: uv sync

      - name: Run Ruff Linter
        run: uv run ruff check .

      - name: Check Code Formatting
        run: uv run ruff format --check .

      - name: Run Pytest Verification Suite
        run: uv run pytest tests/ -v
